server.port=8083

spring.application.name=api-gateway

song.service.name=song-service
resource.service.name=resource-service

# Enable detailed gateway routing logs
logging.level.org.springframework.cloud.gateway=TRACE
# Enable load balancer resolution logs
logging.level.org.springframework.cloud.loadbalancer=DEBUG

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.client.registry-fetch-interval-seconds=5
