server.port=8082
spring.application.name=resource-processor

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.client.registry-fetch-interval-seconds=5

song.service.name=song-service
resource.service.name=resource-service

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.cloud.stream.bindings.resourceUploaded-in-0.destination=resource.uploaded
spring.cloud.stream.bindings.resourceUploaded-in-0.group=resource-processor
spring.cloud.stream.bindings.resourceUploaded-in-0.consumer.max-attempts=3
spring.cloud.stream.bindings.resourceUploaded-in-0.consumer.retryable-exceptions.java.lang.IllegalArgumentException=false
spring.cloud.stream.rabbit.bindings.resourceUploaded-in-0.consumer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.resourceUploaded-in-0.consumer.auto-bind-dlq=true
spring.cloud.stream.rabbit.bindings.resourceUploaded-in-0.consumer.republish-to-dlq=true