server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:../microservices-config-server/common,file:../microservices-config-server/{application},file:../../microservices-config-server/common,file:../../microservices-config-server/{application}}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    org.springframework.cloud.config: WARN
    org.springframework.web: WARN

management:
  endpoints:
    web:
      exposure:
        include: health
